export enum Therapy {
  Oxygen = "Oxygen",
  IVAccess = "IV Access",
  Splint = "Splint",
  SpinalImmobilization = "Spinal Immobilization",
  BleedingControl = "Bleeding Control",
  CPR = "CPR",
  Defibrillation = "Defibrillation",
  Suction = "Suction",
  Dressing = "Dressing",
  AirwayAdjunct = "Airway Adjunct",
  AdvancedAirway = "Advanced Airway",
  EpiAdmin = "Epinephrine Administration",
  GlucoseAdmin = "Glucose Administration",
  MedsAdmin = "Medication Administration",
  Nebulizer = "Nebulizer",
  PainMeds = "Pain Meds",
  Pacing = "Pacing",
  Cardioversion = "Cardioversion",
  AED = "AED",
  AEDAdvised = "AED Advised",
  AEDNoShock = "AED No Shock",
  Other = "Other",
}

export enum MedicalCondition {
  AbdPelvicPain = "Abd/Pelvic pain",
  AllergicReaction = "Allergic Reaction",
  ALTE = "ALTE",
  AlteredLOC = "Altered LOC",
  ApneicEpisode = "Apneic Episode",
  Behavioral = "Behavioral",
  CardiacArrest = "Cardiac Arrest",
  ChestPain = "Chest Pain",
  ChokingAirwayObstruction = "Chock./AW Obst.",
  CoughCongestion = "Cough./Congest.",
  Dysrhythmia = "Dysrhythmia",
  Fever = "Fever",
  ForeignBody = "Foreign Body",
  GIBleed = "GI Bleed",
  HeadPain = "Head Pain",
  LocalNeuroSigns = "Local Neuro Stigs.",
  NauseaVomiting = "Nausea/Vomit",
  NearDrowning = "Near Drowning",
  NeckBackPain = "Neck/Back pain",
  NoseBleeding = "Nose Bleeding",
  ODOrPoisoning = "OD/POisoning",
  Obstetrics = "Obstetrics",
  Labor = "Labor",
  Newborn = "NEWborn",
  Palpitations = "Palpitations",
  RespiratoryArrest = "Resp. Arrest",
  VaginalBleed = "Vaginal bleed",
  InPatientMedical = "In-patient Medical",
  Seizure = "Seizure",
  SOB = "SOB",
  Syncope = "Syncope",
  WeakDizzy = "Weak/Dizzy",
  NoComplaint = "No Complaint",
  OtherPain = "Other Pain",
  Other = "Other",
}

export enum Trauma {
  NoApparentInjury = "No Apparent Injury",
  Shock = "Shock",
  Inpatient = "Inpatient",
  Head = "Head",
  Facial = "Facial",
  Neck = "Neck",
  Chest = "Chest",
  Back = "Back",
  Etremities = "Extremities",
  FRactures = "Fractures",
  Abrasion = "Abrasion",
  NVCompromise = "Neurovascular Compromise",
  MinorLaceration = "Minor Laceration",
  FilialChest = "Flail Chest",
  TrArrest = "Tr. Arrest",
  Genital = "Genit./buttocks",
  Abdoment = "Abdomen",
  DiffuseTenderness = "Diffuse Tenderness",
  Amputation = "Amputation",
  Bite = "Bite",
  Burn = "Burn",
  Crush = "Crush",
  Dislocation = "Dislocation",
  Fracture = "Fracture",
  Laceration = "Laceration",
  PenetratingInjury = "Penetrating Injury",
  SoftTissue = "Soft Tissue",
  SpinalInjury = "Spinal Injury",
  SprainStrain = "Sprain/Strain",
  BluntInjury = "Blunt Injury",
  ImpaledObject = "Impaled Object",
  Other = "Other",
}

export enum MechanismOfInjury {
  MVC = "Motor Vehicle Collision",
  Fall = "Fall",
  Assault = "Assault",
  Sports = "Sports",
  Burn = "Burn",
  Pedestrian = "Pedestrian",
  Bike = "Bike",
  AirBag = "Air Bag",
  ASaault = "Assault",
  WithBlunt = "With Blunt inst.",
  GSW = "GSW",
  TRunk = "TRunk",
  WokrRelated = "Work Related",
  VehicleVsPedestrian = "Vehicle vs Pedestrian",
  Motorcycle = "Motorcycle Vs. Vehicle",
  MotorcycleHelment = "Motorcycle Helmet",
  VehicleRollover = "Vehicle Rollover",
  Seatbelt = "Seatbelt",
  PassSpace = "Passenger Space Intrusion",
  SurFaltal = "Surv. of Fatal acc.",
  Ejection = "Ejected from Vehicle",
  Extractions = "Extrication required",
  Fed = "Fed/Bike vs. Vehicle",
  EncVehicle = "Encapsulated in Vehicle",
  FallGreaterThan2M = "Fall > 2m",
  FallLessThan2M = "Fall < 2m",
  FallGreaterThan5M = "Fall > 5m",
  StabWound = "Stab Wound",
  GunshotWound = "Gunshot Wound",
  Explosion = "Explosion",
  Other = "Other",
}

export enum SkinCondition {
  Normal = "Normal",
  Flushed = "Flushed",
  Pale = "Pale",
  Cyanotic = "Cyanotic",
  Hot = "Hot",
  Cool = "Cool",
  Dry = "Dry",
  Moist = "Moist",
  Diaphoretic = "Diaphoretic",
  CapplillaryRefill = "Capillary Refill Normal",
  CapillaryRefillDelayed = "Capillary Refill Delayed",
}

export enum PupilCondition {
  Normal = "Normal",
  Unequal = "Unequal",
  pinpoint = "Pinpoint",
  RERL = "RERL",
  Fixed = "Fixed",
  Dilated = "Dilated",
  Constricted = "Constricted",
  NonReactive = "Non-Reactive",
  Reactive = "Reactive",
}

export enum Condition {
  CRITICAL = "critical",
  STABLE = "stable",
  SERIOUS = "serious",
  GOOD = "good",
}

export enum RESP {
  Normal = "Normal",
  Clear = "Clear",
  Wheezes = "Wheezes",
  Rhonchi = "Rhonchi",
  Rales = "Rales",
  Apnea = "Apnea",
  Unequal = "Unequal",
  Stridor = "Stridor",
  DecreasedAirEntryR = "Decreased Air Entry R ",
  DecreasedAirEntryL = "Decreased Air Entry L ",
}

export enum SpecialCircumstances {
  DNR = "DNR",
  EMD = "EMD",
  PhysicianOnScene = "Physician on Scene",
  Restraints = "Restraints",
  CPRWithAED = "CPR with AED",
  CPRWithETT = "CPR with ETT",
  WithWitnessedArrest = "Witnessed Arrest",
  WithBystanderCPR = "Bystander CPR",
  WithBystanderAED = "Bystander AED",
  WithAEDUsed = "AED Used",
  TerminationOfResuscitation = "Termination of Resuscitation",
  TraumaTriage = "Trauma Triage",
}

export enum ServerityCode {
  CODE_1 = "CODE-1",
  CODE_2 = "CODE-2",
  CODE_3 = "CODE-3",
}

export enum DietressLevel {
  SEVERE = "Severe",
  MODERATE = "Moderate",
  MILD = "Mild",
  NONE = "None",
}

export enum IncidentCategory {
  MEDICAL = "medical",
  FIRE = "fire",
  CRIME = "crime",
  TRAFFIC_ACCIDENT = "traffic accident",
  NATURAL_DISASTER = "natural disaster",
  HAZMAT = "hazmat",
  SEARCH_AND_RESCUE = "search and rescue",
  UTILITY_FAILURE = "utility failure",
  PUBLIC_DISTURBANCE = "public disturbance",
  OTHER = "other",
}
